FROM ubuntu:18.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        git \
        wget \
        make \
        cmake \
        python \
        build-essential

WORKDIR /root

RUN git clone --single-branch --branch llvmorg-10.0.0 https://github.com/llvm/llvm-project clang10

WORKDIR /root/clang10

ENV CLANG_ROOT /usr/opt/clang-10

RUN mkdir build && \
    cd build && \
    cmake -G 'Unix Makefiles' \
        -DCMAKE_INSTALL_PREFIX='${CLANG_ROOT}' \
        -DLLVM_ENABLE_PROJECTS='lld;polly;clang;clang-tools-extra;libcxx;libcxxabi;libunwind;compiler-rt' \
        -DLLVM_BUILD_LLVM_DYLIB=ON \
        -DLLVM_ENABLE_RTTI=ON \
        -DLLVM_INCLUDE_DOCS=OFF \
        -DLLVM_TARGETS_TO_BUILD=host \
        -DCMAKE_BUILD_TYPE=Release \
            ../llvm && \
    make -j4 && make install

WORKDIR /root

RUN wget https://boostorg.jfrog.io/artifactory/main/release/1.67.0/source/boost_1_67_0.tar.gz && \
    tar xvf boost_1_67_0.tar.gz

WORKDIR /root/boost_1_67_0

ENV BOOST_ROOT /usr/opt/boost

RUN ./bootstrap.sh --with-toolset=clang --prefix=$BOOST_ROOT

RUN bash -c  "./b2 \
    toolset=clang \
    cxxflags=\"-stdlib=libc++ -D__STRICT_ANSI__ -nostdinc++ -I$CLANG_ROOT/include/c++/v1 -D_FORTIFY_SOURCE=2 -fstack-protector-strong -fpie\" \
    linkflags=\'-stdlib=libc++ -pie\' \
    link=static \
    threading=multi \
        --with-iostreams \
        --with-date_time \
        --with-filesystem \
        --with-system \
        --with-program_options \
        --with-chrono \
        --with-test \
    -q -j4 install"

WORKDIR /root

RUN git clone https://github.com/EOSIO/eos.git
WORKDIR /root/eos

RUN git checkout tags/v1.6.6 && git submodule update --init --recursive

RUN cmake .

RUN make -j4 && make install

RUN wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.5.0/eosio.cdt_1.5.0-1_amd64.deb && \
    apt-get install -y ./eosio.cdt_1.5.0-1_amd64.deb

RUN mkdir -p /root/target

WORKDIR /root/target
