FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y git

WORKDIR /root

RUN git clone https://github.com/AntelopeIO/leap.git --recursive --branch v4.0.4

WORKDIR /root/leap

RUN scripts/install_deps.sh

RUN scripts/pinned_build.sh deps build 6

WORKDIR /root/leap/build

RUN curl -L -O https://github.com/AntelopeIO/cdt/releases/download/v4.0.0/cdt_4.0.0_amd64.deb && \
    apt-get install -y -f \
        ./cdt_4.0.0_amd64.deb \
        ./leap_4.0.4-ubuntu22.04_amd64.deb \
        ./leap-dev_4.0.4-ubuntu22.04_amd64.deb


RUN mkdir /root/target

WORKDIR /root/target
