FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
        git \
        wget \
        make cmake \
        build-essential

RUN wget https://github.com/EOSIO/eosio.cdt/releases/download/v1.8.1/eosio.cdt_1.8.1-1-ubuntu-20.04_amd64.deb
RUN apt-get install -y -f ./eosio.cdt_1.8.1-1-ubuntu-20.04_amd64.deb

RUN mkdir -p /root/target

WORKDIR /root/target
